const ADMIN_COLLECTIONS = {
  users: {
    key: "users",
    delegate: "user",
    label: "Users",
    description: "Application accounts and access roles.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "email", label: "Email" },
      { value: "name", label: "Name" },
      { value: "role", label: "Role" },
      { value: "theme", label: "Theme" },
      { value: "selectedFinancialYearStart", label: "FY Start" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [
      { value: "email", label: "Email" },
      { value: "name", label: "Name" },
      { value: "role", label: "Role" },
    ],
    sortableFields: ["createdAt", "updatedAt", "email", "name", "role"],
    hiddenFields: ["password"],
    allowCreate: false,
    allowDelete: false,
  },
  customers: {
    key: "customers",
    delegate: "customer",
    label: "Customers",
    description: "Customer master data used in orders and reports.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "firmName", label: "Firm" },
      { value: "name", label: "Name" },
      { value: "phone", label: "Phone" },
      { value: "gstNo", label: "GST" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [
      { value: "firmName", label: "Firm Name" },
      { value: "name", label: "Name" },
      { value: "phone", label: "Phone" },
      { value: "gstNo", label: "GST" },
    ],
    sortableFields: ["createdAt", "updatedAt", "firmName", "name", "phone"],
    allowCreate: true,
    allowDelete: true,
  },
  manufacturers: {
    key: "manufacturers",
    delegate: "manufacturer",
    label: "Manufacturers",
    description: "Manufacturer master data used in orders and reports.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "firmName", label: "Firm" },
      { value: "name", label: "Name" },
      { value: "phone", label: "Phone" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [
      { value: "firmName", label: "Firm Name" },
      { value: "name", label: "Name" },
      { value: "phone", label: "Phone" },
    ],
    sortableFields: ["createdAt", "updatedAt", "firmName", "name", "phone"],
    allowCreate: true,
    allowDelete: true,
  },
  qualities: {
    key: "qualities",
    delegate: "quality",
    label: "Qualities",
    description: "Quality master records.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "name", label: "Name" },
      { value: "isActive", label: "Active" },
    ],
    searchFields: [{ value: "name", label: "Name" }],
    sortableFields: ["name", "isActive"],
    allowCreate: true,
    allowDelete: true,
  },
  orders: {
    key: "orders",
    delegate: "order",
    label: "Orders",
    description: "Order records and settlement state.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "orderNo", label: "Order No" },
      { value: "status", label: "Status" },
      { value: "quantity", label: "Quantity" },
      { value: "processedQuantity", label: "Processed Qty" },
      { value: "processedMeter", label: "Processed Meter" },
      { value: "commissionAmount", label: "Commission" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [
      { value: "orderNo", label: "Order No", type: "number" },
      { value: "status", label: "Status" },
      { value: "remarks", label: "Remarks" },
      { value: "customerRemark", label: "Customer Remark" },
      { value: "manufacturerRemark", label: "Manufacturer Remark" },
    ],
    sortableFields: [
      "createdAt",
      "updatedAt",
      "orderNo",
      "status",
      "quantity",
      "processedQuantity",
      "processedMeter",
      "commissionAmount",
    ],
    allowCreate: true,
    allowDelete: true,
  },
  pendingPayments: {
    key: "pendingPayments",
    delegate: "pendingPayment",
    label: "Pending Payments",
    description: "Outstanding payment ledger for orders.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "serialNo", label: "Serial No" },
      { value: "accountName", label: "Account" },
      { value: "amountDue", label: "Amount Due" },
      { value: "amountReceived", label: "Received" },
      { value: "balanceAmount", label: "Balance" },
      { value: "status", label: "Status" },
    ],
    searchFields: [
      { value: "accountName", label: "Account" },
      { value: "status", label: "Status" },
      { value: "serialNo", label: "Serial No", type: "number" },
    ],
    sortableFields: ["createdAt", "updatedAt", "serialNo", "amountDue", "balanceAmount", "status"],
    allowCreate: true,
    allowDelete: true,
  },
  paymentReceipts: {
    key: "paymentReceipts",
    delegate: "paymentReceipt",
    label: "Payment Receipts",
    description: "Payment receipt entries.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "serialNo", label: "Serial No" },
      { value: "accountName", label: "Account" },
      { value: "amount", label: "Amount" },
      { value: "paymentMode", label: "Mode" },
      { value: "date", label: "Date" },
    ],
    searchFields: [
      { value: "accountName", label: "Account" },
      { value: "paymentMode", label: "Mode" },
      { value: "serialNo", label: "Serial No", type: "number" },
    ],
    sortableFields: ["createdAt", "updatedAt", "serialNo", "amount", "date"],
    allowCreate: true,
    allowDelete: true,
  },
  paymentAllocations: {
    key: "paymentAllocations",
    delegate: "paymentAllocation",
    label: "Payment Allocations",
    description: "Allocated receipt amounts against pending payments.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "allocatedAmount", label: "Allocated" },
      { value: "isFinalSettlement", label: "Final Settlement" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [{ value: "isFinalSettlement", label: "Final Settlement", type: "boolean" }],
    sortableFields: ["createdAt", "updatedAt", "allocatedAmount"],
    allowCreate: true,
    allowDelete: true,
  },
  orderActivities: {
    key: "orderActivities",
    delegate: "orderActivity",
    label: "Order Activities",
    description: "Immutable order change history.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "action", label: "Action" },
      { value: "orderId", label: "Order ID" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [{ value: "action", label: "Action" }],
    sortableFields: ["createdAt", "action"],
    allowCreate: false,
    allowDelete: false,
  },
  remarkTemplates: {
    key: "remarkTemplates",
    delegate: "remarkTemplate",
    label: "Remark Templates",
    description: "Saved remark snippets.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "text", label: "Text" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [{ value: "text", label: "Text" }],
    sortableFields: ["createdAt", "updatedAt", "text"],
    allowCreate: true,
    allowDelete: true,
  },
  whatsappGroups: {
    key: "whatsappGroups",
    delegate: "whatsAppGroup",
    label: "WhatsApp Groups",
    description: "Saved WhatsApp group links.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "name", label: "Name" },
      { value: "inviteLink", label: "Invite Link" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [{ value: "name", label: "Name" }],
    sortableFields: ["createdAt", "updatedAt", "name"],
    allowCreate: true,
    allowDelete: true,
  },
  yearTransferBatches: {
    key: "yearTransferBatches",
    delegate: "yearTransferBatch",
    label: "Year Transfer Batches",
    description: "Financial year carry-forward batches.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "sourceFyStartYear", label: "From FY" },
      { value: "targetFyStartYear", label: "To FY" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [
      { value: "sourceFyStartYear", label: "From FY", type: "number" },
      { value: "targetFyStartYear", label: "To FY", type: "number" },
    ],
    sortableFields: ["createdAt", "updatedAt", "sourceFyStartYear", "targetFyStartYear"],
    allowCreate: false,
    allowDelete: false,
  },
  passwordResetTokens: {
    key: "passwordResetTokens",
    delegate: "passwordResetToken",
    label: "Password Reset Tokens",
    description: "Password reset token records.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "userId", label: "User ID" },
      { value: "expiresAt", label: "Expires At" },
      { value: "usedAt", label: "Used At" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [{ value: "userId", label: "User ID" }],
    sortableFields: ["createdAt", "expiresAt", "usedAt"],
    hiddenFields: ["token"],
    allowCreate: false,
    allowDelete: true,
  },
  adminActionLogs: {
    key: "adminActionLogs",
    delegate: "adminActionLog",
    label: "Admin Action Logs",
    description: "Audit log for admin-side data changes.",
    previewFields: [
      { value: "id", label: "ID" },
      { value: "action", label: "Action" },
      { value: "collectionKey", label: "Collection" },
      { value: "recordId", label: "Record ID" },
      { value: "createdAt", label: "Created" },
    ],
    searchFields: [
      { value: "action", label: "Action" },
      { value: "collectionKey", label: "Collection" },
      { value: "recordId", label: "Record ID" },
    ],
    sortableFields: ["createdAt", "action", "collectionKey"],
    allowCreate: false,
    allowUpdate: false,
    allowDelete: false,
  },
};

function getAdminCollectionKeys() {
  return Object.keys(ADMIN_COLLECTIONS);
}

function getAdminCollectionConfig(collectionKey) {
  return ADMIN_COLLECTIONS[collectionKey] || null;
}

module.exports = {
  ADMIN_COLLECTIONS,
  getAdminCollectionKeys,
  getAdminCollectionConfig,
};
